### ISSUE TITLE
Finding a space 

### ISSUE THREAD

**Issue by intersectto** [intersectto/BIPOC-Hackathon#1]
Dates of interest: weekend of July 28th or August 11th

- [x] Al to ontact Elisa about CSI
- [x] Al to contact DMZ folks
- [x] Lequanne to contact Regent Park CSI folks

**Comment by aljumaine** [comment]
On June 6, 2018 - Our team confirmed to host our event with The Parkdale Centre for Innovation on July 28th! :)
