### ISSUE TITLE
Recruit Project Submission / Idea's (Leads) - June 10

### ISSUE THREAD

**Issue by lequanne** [intersectto/BIPOC-Hackathon#10]
Lorraine does first draft  
Have the link to the google form done for Lequanne to add to the website

**Comment by lorrainechu3n** [comment]
I'm behind on this and will have it done by tomorrow!

**Comment by char-siuu-bao** [comment]
@aljumaine @lequanne @byvivian I was able to draft a google form for project leads - what do you think?  https://docs.google.com/forms/d/e/1FAIpQLSea4ToQQQtztgLwGEcrg4kraIn-KFkAO1X7asZIlLIFkyDIfQ/viewform

**Comment by aljumaine** [comment]
@lorrainechu3n - I just had a look at the form and its perfect. Awesome work and that was really fast. 

https://docs.google.com/forms/d/e/1FAIpQLSea4ToQQQtztgLwGEcrg4kraIn-KFkAO1X7asZIlLIFkyDIfQ/viewform

**Comment by byvivian** [comment]
@lorrainechu3n looks good! would a question about what kind of roles are needed be helpful? like a visual-heavy project might want some visual designers, etc.? otherwise, it's good!
