### ISSUE TITLE
Research around Youth Events

### ISSUE THREAD

**Issue by lequanne** [intersectto/BIPOC-Hackathon#13]

**Comment by char-siuu-bao** [comment]
I've drafted a parental permission form here - also asks for an emergency contact https://docs.google.com/document/d/1OBQ9ACFwF8wQH-Rd2mLhVozOKnc0MtBqEU4Di2U4duc/edit# 

I referred back to how Canada Learning Code asks for permission for their Teen events, and they just have a check box asking for parental permission in the Eventbrite page.  So I think the above form would cover what we need, but also down to do more research!
