### ISSUE TITLE
Confirm Agenda

### ISSUE THREAD

**Issue by lequanne** [intersectto/BIPOC-Hackathon#17]

**Comment by aljumaine** [comment]
Hey team, I have prepared a rough draft of the agenda for the event. 
Thanks! 

**Agenda Break Down - Draft 1**
https://docs.google.com/document/d/1Ev0B41MRCC_57CiN0Dd4Cd1jtUsfC_i9jw3aKaKZzao/edit#heading=h.fr5gs3mlycm9

**Comment by byvivian** [comment]
edited/added comments
