### ISSUE TITLE
Write Code of Conduct  - May 30

### ISSUE THREAD

**Issue by lequanne** [intersectto/BIPOC-Hackathon#3]
Review code of conduct. 

Examples to pull from:
[Code of Conduct developer ](https://www.mozillapulse.org/entry/674)
[Code of Conduct for hackathons](https://hackcodeofconduct.org/)
[OpenCon 2017](https://www.opencon2017.org/code_of_conduct)

Deadline May 30.

**Comment by aljumaine** [comment]
Thanks, Lequanne for sharing these great examples. Please find below my first draft for review.

https://docs.google.com/document/d/1C1OgXRYF8tRheoWDNdauzXECiuc7aTWuj2Q4jEU6PtM/edit#

**Comment by byvivian** [comment]
Looks good - just made some very minor edits and formatting
